### ISSUE TITLE
CAS proxy tickets support

### ISSUE THREAD

**Issue by dima767** [casinthecloud/java-shiro-cas-client-demo#1]
Hey Jerome,

can you take a look? https://issues.apache.org/jira/browse/SHIRO-402

Possible?

**Comment by leleuj** [comment]
It makes sense to add CAS proxy support to Shiro. I had that in my roadmap, but no motivation to do it.

It's feasible. I have to finish first CAS-1183 and CAS-1235. I'll work on that at the beginning of 2013...

**Comment by dima767** [comment]
I guess this could be closed.

**Comment by leleuj** [comment]
Thanks for cleaning ;-)

Proxy mechanism is supported using the buji-pac4j extension. The shiro-cas support may disappear in favor of it.
